platform :ios, '7.0'
pod 'AFNetworking', '~> 2.0'
pod 'apptentive-ios'
pod 'ZipArchive'
#pod 'CorePlot'
pod 'CorePlot', '~>1.6'
pod 'CocoaLumberjack'
pod 'AWSS3'
xcodeproj 'SalutronFitnessApp/SalutronFitnessApp.xcodeproj'
